// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rDHdjMfnipijvJWMTFaaznFweT3Hw8E',
    appId: '1:27790730882:web:63141b6585fef07a0e769b',
    messagingSenderId: '27790730882',
    projectId: 'vigilai-f70e2',
    authDomain: 'vigilai-f70e2.firebaseapp.com',
    storageBucket: 'vigilai-f70e2.firebasestorage.app',
    measurementId: 'G-LX35RM5KK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhTe2RFZH1VFingNh-oSpSSJvM8k3sVw',
    appId: '1:27790730882:android:bd91eef7cc46069a0e769b',
    messagingSenderId: '27790730882',
    projectId: 'vigilai-f70e2',
    storageBucket: 'vigilai-f70e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqOhGhayEmuX8iT3M7_PldK3kvBm4G58Y',
    appId: '1:27790730882:ios:4ffc8970e2985e480e769b',
    messagingSenderId: '27790730882',
    projectId: 'vigilai-f70e2',
    storageBucket: 'vigilai-f70e2.firebasestorage.app',
    iosBundleId: 'com.example.vigilDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqOhGhayEmuX8iT3M7_PldK3kvBm4G58Y',
    appId: '1:27790730882:ios:4ffc8970e2985e480e769b',
    messagingSenderId: '27790730882',
    projectId: 'vigilai-f70e2',
    storageBucket: 'vigilai-f70e2.firebasestorage.app',
    iosBundleId: 'com.example.vigilDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9rDHdjMfnipijvJWMTFaaznFweT3Hw8E',
    appId: '1:27790730882:web:cfadae36725f30480e769b',
    messagingSenderId: '27790730882',
    projectId: 'vigilai-f70e2',
    authDomain: 'vigilai-f70e2.firebaseapp.com',
    storageBucket: 'vigilai-f70e2.firebasestorage.app',
    measurementId: 'G-NF29TQJLQJ',
  );
}
